"""
memory_store.py — Agent Memory Stream (v4.3).

Cross-session memory for PhytoReason agents. Inspired by Stanford Smallville
memory stream but simplified for scientific use.

Features:
- Persistent memory storage (same SQLite DB as sessions)
- Importance-weighted scoring (1-10)
- Recency decay (1-week half-life)
- TF-IDF relevance search
- Auto-consolidation: summarize recent observations into reflections
- Tag-based retrieval (species, metabolite, gene family)

Memory types:
    observation  — raw fact observed during conversation
    reflection   — higher-level insight generated by consolidation
    preference   — user-stated preference or constraint
    result       — analysis result worth remembering
"""

from __future__ import annotations

import json
import logging
import math
import sqlite3
import threading
import time
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger("memory_store")

# ── DB schema ──────────────────────────────────────────────────

CREATE_MEMORIES_TABLE = """
CREATE TABLE IF NOT EXISTS memories (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id      TEXT NOT NULL,
    content         TEXT NOT NULL,
    memory_type     TEXT DEFAULT 'observation',
    importance      INTEGER DEFAULT 5,
    tags            TEXT DEFAULT '[]',
    species         TEXT DEFAULT '',
    metabolite      TEXT DEFAULT '',
    created_at      TEXT NOT NULL,
    last_accessed   TEXT,
    access_count    INTEGER DEFAULT 0
);
"""

CREATE_MEMORIES_INDEX = """
CREATE INDEX IF NOT EXISTS idx_memories_type
ON memories(memory_type);

CREATE INDEX IF NOT EXISTS idx_memories_created
ON memories(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_memories_species
ON memories(species) WHERE species != '';

CREATE INDEX IF NOT EXISTS idx_memories_importance
ON memories(importance DESC);
"""

# ── Helpers ────────────────────────────────────────────────────

def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()

def _hours_since(iso_str: str) -> float:
    """Compute hours elapsed since an ISO timestamp."""
    try:
        dt = datetime.fromisoformat(iso_str)
        delta = datetime.now(timezone.utc) - dt
        return delta.total_seconds() / 3600.0
    except Exception:
        return 0.0

def _tokenize(text: str) -> list[str]:
    """Simple tokenizer for TF-IDF."""
    import re
    return re.findall(r"[a-zA-Z一-鿿]+", text.lower())


# ═══════════════════════════════════════════════════════════════
# MemoryEntry
# ═══════════════════════════════════════════════════════════════

@dataclass
class MemoryEntry:
    """A single memory in the stream."""
    session_id: str
    content: str
    memory_type: str = "observation"
    importance: int = 5
    tags: list[str] = field(default_factory=list)
    species: str = ""
    metabolite: str = ""
    created_at: str = field(default_factory=_now_iso)
    last_accessed: str | None = None
    access_count: int = 0
    id: int | None = None


# ═══════════════════════════════════════════════════════════════
# MemoryStore
# ═══════════════════════════════════════════════════════════════

class MemoryStore:
    """Cross-session memory stream with hybrid retrieval.

    Retrieval scoring:
        final = 0.50 × relevance + 0.25 × recency + 0.25 × importance

    Usage:
        store = MemoryStore()
        store.add(MemoryEntry(session_id="...", content="WRKY1 r=0.85 with BBE", ...))
        results = store.search("WRKY berberine regulation", top_k=5)
    """

    def __init__(self, db_path: str | None = None) -> None:
        if db_path is None:
            from phyto_reason.platform_paths import memory_db_path
            db_path = str(memory_db_path())

        self._db_path = str(db_path)
        self._lock = threading.Lock()
        self._init_db()

        # TF-IDF cache (rebuilt on search)
        self._chunks: list[dict] = []
        self._vocab: dict[str, int] = {}
        self._vectors: Any = None
        self._index_version: int = 0

        logger.info("MemoryStore ready: db=%s", self._db_path)

    # ═══════════════════════════════════════════════════════════
    # Public API
    # ═══════════════════════════════════════════════════════════

    def add(self, entry: MemoryEntry) -> int:
        """Add a memory. Returns the new row ID."""
        with self._lock:
            memory_id = self._insert(entry)
            self._index_version += 1  # invalidate TF-IDF cache
            return memory_id

    def add_observation(
        self,
        content: str,
        session_id: str = "",
        importance: int = 5,
        tags: list[str] | None = None,
        species: str = "",
        metabolite: str = "",
    ) -> int:
        """Convenience: add an observation-type memory."""
        return self.add(MemoryEntry(
            session_id=session_id,
            content=content,
            memory_type="observation",
            importance=importance,
            tags=tags or [],
            species=species,
            metabolite=metabolite,
        ))

    def add_result(
        self,
        content: str,
        session_id: str = "",
        importance: int = 7,
        tags: list[str] | None = None,
        species: str = "",
        metabolite: str = "",
    ) -> int:
        """Convenience: add a result-type memory (higher importance default)."""
        return self.add(MemoryEntry(
            session_id=session_id,
            content=content,
            memory_type="result",
            importance=importance,
            tags=tags or [],
            species=species,
            metabolite=metabolite,
        ))

    def add_preference(
        self,
        content: str,
        session_id: str = "",
        importance: int = 6,
    ) -> int:
        """Convenience: add a user preference."""
        return self.add(MemoryEntry(
            session_id=session_id,
            content=content,
            memory_type="preference",
            importance=importance,
        ))

    def search(self, query: str, top_k: int = 5) -> list[dict]:
        """Hybrid search: TF-IDF relevance + recency + importance.

        Returns list of dicts with: id, content, memory_type, importance,
        tags, species, metabolite, created_at, score (0-1).
        """
        with self._lock:
            all_memories = self._fetch_all()
            if not all_memories:
                return []

            # Ensure TF-IDF index is current
            self._ensure_index(all_memories)

            # Compute TF-IDF relevance
            relevance_scores = self._relevance_scores(query, len(all_memories))

            results = []
            for i, row in enumerate(all_memories):
                if i >= len(relevance_scores):
                    continue

                relevance = relevance_scores[i]
                recency = self._recency_score(row["created_at"])
                importance = self._importance_score(row["importance"])

                final = 0.50 * relevance + 0.25 * recency + 0.25 * importance

                # Skip completely irrelevant unless tagged match
                if relevance < 0.01 and final < 0.05:
                    continue

                results.append({
                    "id": row["id"],
                    "content": row["content"],
                    "memory_type": row["memory_type"],
                    "importance": row["importance"],
                    "tags": self._safe_json_load(row["tags"], []),
                    "species": row["species"],
                    "metabolite": row["metabolite"],
                    "created_at": row["created_at"],
                    "score": round(final, 4),
                    "relevance": round(relevance, 4),
                    "recency": round(recency, 4),
                })

            results.sort(key=lambda r: r["score"], reverse=True)
            selected = results[:top_k]

            # Update access stats
            for r in selected:
                self._touch_access(r["id"])

            return selected

    def get_recent(self, n: int = 10) -> list[dict]:
        """Get most recent memories."""
        with self._lock:
            rows = self._fetch_recent(n)
            return [self._row_to_dict(r) for r in rows]

    def get_by_tag(self, tag: str, n: int = 10) -> list[dict]:
        """Get memories by tag."""
        with self._lock:
            rows = self._fetch_by_tag(tag, n)
            return [self._row_to_dict(r) for r in rows]

    def get_by_species(self, species: str, n: int = 10) -> list[dict]:
        """Get memories by species."""
        with self._lock:
            rows = self._fetch_by_field("species", species, n)
            return [self._row_to_dict(r) for r in rows]

    def count(self) -> int:
        """Total memory count."""
        try:
            with self._get_conn() as conn:
                row = conn.execute("SELECT COUNT(*) FROM memories").fetchone()
                return row[0] if row else 0
        except sqlite3.Error:
            return 0

    def consolidate(self, llm_client=None) -> int:
        """Consolidate recent observations into a reflection.

        If llm_client is provided, uses it to generate a higher-level summary.
        Otherwise, creates a simple keyword-based summary.

        Returns number of new reflection memories created.
        """
        observations = self.get_recent(20)
        # Filter to only observation type
        obs = [m for m in observations if m.get("memory_type") == "observation"]
        if len(obs) < 5:
            return 0  # not enough to consolidate

        # Build summary text
        contents = [m["content"] for m in obs[:15]]

        if llm_client is not None:
            prompt = (
                "You are an agent memory consolidator. Below are recent observations "
                "from PhytoReason analysis sessions. Synthesize them into 1-3 key insights "
                "or patterns. Be concise (1-2 sentences each).\n\n"
                + "\n".join(f"- {c}" for c in contents)
            )
            try:
                summary = llm_client.chat([{"role": "user", "content": prompt}], temperature=0.3)
            except Exception:
                summary = "; ".join(contents[:3])[:500]
        else:
            summary = "; ".join(contents[:5])[:500]

        # Save as reflection
        if summary.strip():
            return self.add(MemoryEntry(
                session_id="consolidation",
                content=summary.strip(),
                memory_type="reflection",
                importance=8,
            ))

        return 0

    # ═══════════════════════════════════════════════════════════
    # Scoring
    # ═══════════════════════════════════════════════════════════

    @staticmethod
    def _recency_score(created_at: str) -> float:
        """Exponential recency decay: 1-week half-life, range 0-1."""
        hours = _hours_since(created_at)
        # Clamp: negative hours (future/clock-drift timestamps) → treat as now
        if hours < 0:
            hours = 0.0
        # Half-life = 168 hours (1 week)
        return math.exp(-hours * math.log(2) / 168.0)

    @staticmethod
    def _importance_score(importance: int) -> float:
        """Normalize importance 1-10 to 0-1 range."""
        return max(0.0, min(1.0, (importance - 1) / 9.0))

    # ═══════════════════════════════════════════════════════════
    # TF-IDF
    # ═══════════════════════════════════════════════════════════

    def _ensure_index(self, memories: list[dict]) -> None:
        """Build TF-IDF index if stale."""
        if self._vectors is not None and len(self._chunks) == len(memories):
            return  # still valid

        texts = [m["content"] for m in memories]
        stopwords = {"the", "a", "an", "is", "are", "was", "were", "of", "in",
                     "to", "and", "for", "on", "with", "as", "at", "by", "or",
                     "this", "that", "from", "it", "its", "be", "has", "have"}

        doc_freq: Counter = Counter()
        all_tokens: list[list[str]] = []
        for t in texts:
            tokens = [w for w in _tokenize(t) if w not in stopwords and len(w) > 1]
            all_tokens.append(tokens)
            doc_freq.update(set(tokens))

        top_words = [w for w, _ in doc_freq.most_common(1000)]
        self._vocab = {w: i for i, w in enumerate(top_words)}

        if not self._vocab:
            self._vectors = None
            self._chunks = [{"text": t} for t in texts]
            return

        import numpy as np

        n = len(texts)
        idf = np.zeros(len(self._vocab))
        for w, i in self._vocab.items():
            df = doc_freq[w]
            idf[i] = math.log((n + 1) / (df + 1)) + 1

        vecs = np.zeros((n, len(self._vocab)), dtype=np.float32)
        for i, tokens in enumerate(all_tokens):
            tf = Counter(tokens)
            for w, c in tf.items():
                if w in self._vocab:
                    vecs[i, self._vocab[w]] = c * idf[self._vocab[w]]

        norms = np.linalg.norm(vecs, axis=1, keepdims=True)
        norms[norms == 0] = 1
        self._vectors = vecs / norms
        self._chunks = [{"text": t} for t in texts]

    def _relevance_scores(self, query: str, n_docs: int) -> list[float]:
        """Compute TF-IDF cosine similarity for query against all documents."""
        if self._vectors is None:
            return [0.0] * n_docs

        import numpy as np

        qt = _tokenize(query)
        qv = np.zeros(len(self._vocab), dtype=np.float32)
        for w in qt:
            if w in self._vocab:
                qv[self._vocab[w]] += 1
        qn = np.linalg.norm(qv)
        if qn > 0:
            qv /= qn

        scores = self._vectors @ qv
        return [max(0.0, float(s)) for s in scores]

    # ═══════════════════════════════════════════════════════════
    # DB operations
    # ═══════════════════════════════════════════════════════════

    def _init_db(self) -> None:
        try:
            with self._get_conn() as conn:
                conn.execute(CREATE_MEMORIES_TABLE)
                conn.executescript(CREATE_MEMORIES_INDEX)
                conn.commit()
        except sqlite3.Error as e:
            logger.error("Failed to init memory DB: %s", e)

    def _get_conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self._db_path, check_same_thread=False)
        conn.execute("PRAGMA journal_mode=WAL")
        conn.row_factory = sqlite3.Row
        return conn

    def _insert(self, entry: MemoryEntry) -> int:
        try:
            with self._get_conn() as conn:
                cur = conn.execute("""
                    INSERT INTO memories (session_id, content, memory_type,
                        importance, tags, species, metabolite, created_at)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    entry.session_id,
                    entry.content,
                    entry.memory_type,
                    entry.importance,
                    json.dumps(entry.tags, ensure_ascii=False),
                    entry.species,
                    entry.metabolite,
                    entry.created_at,
                ))
                conn.commit()
                return cur.lastrowid
        except sqlite3.Error as e:
            logger.error("Failed to insert memory: %s", e)
            return -1

    def _fetch_all(self) -> list[dict]:
        try:
            with self._get_conn() as conn:
                rows = conn.execute(
                    "SELECT * FROM memories ORDER BY created_at DESC"
                ).fetchall()
            return [dict(r) for r in rows]
        except sqlite3.Error:
            return []

    def _fetch_recent(self, n: int) -> list[sqlite3.Row]:
        try:
            with self._get_conn() as conn:
                return conn.execute(
                    "SELECT * FROM memories ORDER BY created_at DESC LIMIT ?", (n,)
                ).fetchall()
        except sqlite3.Error:
            return []

    def _fetch_by_tag(self, tag: str, n: int) -> list[sqlite3.Row]:
        try:
            with self._get_conn() as conn:
                return conn.execute(
                    "SELECT * FROM memories WHERE tags LIKE ? ORDER BY created_at DESC LIMIT ?",
                    (f"%{tag}%", n),
                ).fetchall()
        except sqlite3.Error:
            return []

    def _fetch_by_field(self, field: str, value: str, n: int) -> list[sqlite3.Row]:
        try:
            with self._get_conn() as conn:
                return conn.execute(
                    f"SELECT * FROM memories WHERE {field}=? ORDER BY created_at DESC LIMIT ?",
                    (value, n),
                ).fetchall()
        except sqlite3.Error:
            return []

    def _touch_access(self, memory_id: int) -> None:
        try:
            with self._get_conn() as conn:
                conn.execute(
                    "UPDATE memories SET last_accessed=?, access_count=access_count+1 WHERE id=?",
                    (_now_iso(), memory_id),
                )
                conn.commit()
        except sqlite3.Error:
            pass

    @staticmethod
    def _safe_json_load(text: str | None, default=None):
        if not text:
            return default
        try:
            return json.loads(text)
        except (json.JSONDecodeError, TypeError):
            return default

    def _row_to_dict(self, row: sqlite3.Row) -> dict:
        return {
            "id": row["id"],
            "content": row["content"],
            "memory_type": row["memory_type"],
            "importance": row["importance"],
            "tags": self._safe_json_load(row["tags"], []),
            "species": row["species"],
            "metabolite": row["metabolite"],
            "created_at": row["created_at"],
        }


# ── Global singleton ───────────────────────────────────────────

memory_store = MemoryStore()
